[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
image = "0.25.9"
indicatif = "0.18.3"
rayon = "1.11.0"
regex = "1.12.2"
